project:
  type: website

website:
  title: "Susy Echeverria-Londono"
  navbar:
    right:
      - href: index.qmd
        text: About
      - href: experience.qmd
        text: Experience
      - href: education.qmd
        text: Education
      - href: publications.qmd
        text: Publications
      - text: "CV in English"
        href: "cv/index_English.qmd"
      - text: "CV en français"
        href: "cv/index_French.qmd"
  page-footer: "Copyright 2024 &copy; Susy Echeverria-Londono"


format:
  html:
    theme: cosmo
    css: styles.css
    link-external-newwindow: true
