project:
  type: website

website:
  title: "Susy Echeverria-Londono"
  navbar:
    right:
      - href: index.qmd
        text: About
      - href: education.qmd
        text: Education
      - href: publications.qmd
        text: Publications
      - href: visualisations.qmd
        text: Visualisations


format:
  html:
    theme: [sandstone, _variables.scss]
    toc: true
    link-external-newwindow: true
    

editor: source
