---
title: "Biodiversity work"
---

-   

    2021. Neves, D.M., Kerkhoff, A.J., Echeverría-Londoño, S,. Merow, C., Morueta-Holme, N., Peet, R.K., Sandel, B., Svenning, J.C., Wiser, S.K. and Enquist, B.J. The adaptive challenge of extreme conditions shapes evolutionary diversity of plant assemblages at continental scales, Proceedings of the National Academy of Sciences 118(37). https://doi.org/10.1073/pnas.202113211

-   

    2020. Laiton-Donato, K., Villabona-Arenas, CJ., Usme-Ciro, J., Franco-Mu\~noz., C, 'Alvarez-D'iaz, D., Villabona-Arenas, LS., Echeverr'ia-Londo\~no, S,. et al., Genomic epidemiology of severe acute respiratory syndrome coronavirus 2, Colombia. Emerging infectious diseases, 26, no. 12: 2854. https://doi.org/10.3201/eid2612.202969

-   

    2020. Echeverr'ia-Londo\~no, S,. S"arkinen, T., Fenton, I. S., Knapp, S. and Purvis, A. Dynamism and context dependency in the diversification of the megadiverse plant genus Solanum L. (Solanaceae), Journal of Systematics and Evolution, 58(6), 767-782. https://doi.org/10.1111/jse.12638

-   

    2018. Echeverr'ia-Londo\~no, S., Enquist. B. J., Neves, D. M., Violle, C. and Kerkhoff, A. J. Plant functional diversity and the biogeography of biomes in North and South America. Frontiers in Ecology and Evolution, 6(DEC), 219. https://doi.org/10.3389/fevo.2018.00219

-   

    2017. Isaacs, P., Echeverr'ia-Londo\~no, S., Urbina, N. and Purvis, A. Species composition and changes in land use: considerations under climatic change scenarios. Moreno, L. A., Andrade, G. I. and Ru'iz-Contreras, L. F. (Editors). In Biodiversity 2016. Status and Trends of Colombian Continental Biodiversity, Instituto de Investigaci'on de Recursos Biol'ogicos Alexander von Humboldt, 106 p. http://reporte.humboldt.org.co/biodiversity/2016/cap2/203/index.html

-   

    2017. Hudson, L. N., Newbold, T., Contu, S., Hill, S. L., Lysenko, I., De Palma, A., Diaz, S., Echeverr'ia-Londo\~no, S., \dots and Purvis, A. The database of the PREDICTS (Projecting Responses of Ecological Diversity in Changing Terrestrial Systems) project, Ecology and Evolution, 7(1), 145--188. https://doi.org/10.1002/ece3.2579

-   

    2016. Echeverr'ia-Londo\~no, S., Newbold, T., Hudson, L. N., Hill, S. L., Contu, S., Lysenko, I., \dots and Purvis, A. Modelling and projecting the response of Colombian biodiversity to land-use change, Diversity and Distributions, 22, 1099--1111. https://doi.org/10.1111/ddi.12478

-   

    2015. Newbold, T., Hudson, L. N., Hill, S. L., Contu, S., Lysenko, I., Senior, R. A., Bennet D. J., Choimes A., Collen, B., Day, J., De Palma, A., Diaz, S., Echeverr'ia-Londo\~no, S., \dots and Purvis, A. Global effects of land use on local terrestrial biodiversity, Nature, 520(7545), 45--50. https://doi.org/10.1038/nature14324

-   

    2014. Newbold, T., Hudson, L. N., Contu, S., Hill, S. L., Lysenko, I., De Palma, A., Phillips, H., Senior, R. A., Bennet D. J., Booth, H., Choimes, A., Correia, D. L. P., Day, J., Echeverr'ia-Londo\~no, S., \dots and Purvis, A. The PREDICTS database: a global database of how local terrestrial biodiversity responds to human impacts, Ecology and Evolution, 4(24), 4701--4735. https://doi.org/10.1002/ece3.1303

-   

    2011. Echeverr'ia-Londo\~no, S. and Miranda-Esquivel, D. R. MartiTracks: A geometrical approach for identifying geographical patterns of distribution, PLoS ONE, 6(4), e18460. https://doi.org/10.1371/journal.pone.0018460

-   

    2010. Miranda-Esquivel, D. R., Morales-Guerrero, A. M. and Echeverr'ia-Londo\~no, S. \textquestiondown Cu'antos somos? y \textquestiondown C'omo nos cuantificamos? In Evoluci'on \`\`Historia de la Vida". Asociaci'on Colombiana para el avance de la Ciencia ACAC. ISBN: 978-958-9457-67-2
