---
title: "Professional experience"
---

## Research Consultant (2022--present)

- Imperial College London, UK, Vaccine Impact Modelling Consortium (VIMC), Department of Infectious Disease Epidemiology. PI: Prof.Caroline Trotter. Line manager:  Dr Katy Gaythorpe

- Collaborated with the science and policy team at VIMC to analyse and incorporate the impact estimates of various vaccines assessed in the GAVI's Vaccine Investment Strategy 2024.

## Research Consultant and Research Associate (2019--2022)

- Imperial College London, UK. Vaccine Impact Modelling Consortium (VIMC), Department of Infectious Disease Epidemiology.PI: Prof. Neil M. Ferguson. Line manager:  Dr Katy Gaythorpe.

- Conducted thorough analysis, organisation, and preparation of vaccine impact estimates for 12 pathogens (Cholera, HepB, Hib, HPV, Japanese encephalitis, Measles, MenA, PCV, Rotavirus, Rubella, Typhoid, Yellow fever) across 112 countries spanning from 2000 to 2030, incorporating multiple estimates from diverse modelling groups for each pathogen.

- Extracted and standardised subnational estimates of vaccine coverage to project the impact of routine measles vaccination across 45 African countries while investigating subnational disparities within these regions from 2000 to 2019.  

- Assisted in the development of methods for aggregation and analysis of disease burden and vaccine impact estimates derived from various epidemiological models.

- Examined the effects of COVID-19 pandemic on immunisation activities for 14 pathogens (Diphtheria, HPV, HepB, HIB, Japanese encephalitis, Measles, MenA, PCV, Pertussis, Rotavirus, Rubella, Tetanus, Typhoid, Yellow fever). 

- Published research findings in high-quality academic journals.

- Produced regular analytical reports for international organisations and funding bodies such as the Vaccine Alliance (GAVI), the Bill \& Melinda Gates Foundation (BMGF), and the World Health Organisation (WHO).

- Supported the Imperial College Ebola Response Team in evaluating the effectiveness and reliability of real-time outbreak analysis during multiple Ebola Virus Disease outbreaks in the Democratic Republic of the Congo.

- Assisted in the preparation of weekly real-time reports on Ebola outbreaks for the World Health Organization (WHO).

## Visiting Scholar (2018--2019)

- University of Pittsburgh, PA, USA. Biological Sciences Department. PI: Dr. Justin Kitzes. 
- Assessed and predicted extinction risks for 300 plant species through comprehensive exploration and analysis of their spatial time-series data using spatial point pattern analysis

## NSF Postdoctoral Associate (2017--2019)

- Kenyon College, OH, USA. Biology department. PI: Prof. Andrew Kerkhoff and Prof. Brian J. Enquist. 

- Conducted an extensive analysis of functional diversity distributions among plant species across the biomes of North and South America. Used distribution data from approximately 85,000 plant species, comprising around 9 million geographic points, in conjunction with publicly available functional traits.

- Investigated the influence of habitat stability on current patterns of plant diversity analysing of the distribution and phylogenetic relationships among approximately 24,000 plant species.

- Used random forest analysis to conduct paleohabitat reconstructions to understand the evolution of biomes in North and South America. 

- Co-taught the BSc course ``Global Ecology and Biogeography''.

## Lecturer & demonstrator (2013--2017)

- Natural History Museum & Imperial College London, UK
- Lectured and demonstrated for several quantitative courses in the Taxonomy and Biodiversity MSc and Life Sciences BSc programmes.
