---
title: "Public Health work"
---

(2023) Hartner, A. M., Li, X., Echeverr\'ia-Londo\~no, S,. Roth, J., Abbas, K., Auzenbergs, M., ... \& Gaythorpe, K. COVID-19 Related Immunisation Disruptions from 2020-2030: Projecting Health Impact and Mitigation Strategies for 14 Pathogens Across 112 Low(and Middle-Income Countries. Available at SSRN: https://ssrn.com/abstract=4492698 or http://dx.doi.org/10.2139/ssrn.4492698

(2022) Ali, H.A., Hartner, AM., Echeverr\'ia-Londo\~no, S,.. \& et al. Vaccine equity in low and middle-income countries: a systematic review and meta-analysis. Int J Equity Health 21, 82. https://doi.org/10.1186/s12939-022-01678-5

(2022) Echeverr\'ia-Londo\~no, S,.  Hartner, A. M., Li, X., Roth, J., Portnoy, A., Sbarra, A. N., ... \& Gaythorpe, K. A. Exploring the subnational inequality and heterogeneity of the impact of routine measles immunisation in Africa. Vaccine, 40(47), 6806-6817. https://doi.org/10.1016/j.vaccine.2022.09.049

(2022) Toor, J., Li, X., Jit, M., Trotter, C. L., Echeverr\'ia-Londo\~no, S,.  Hartner, A. M., ... \& Gaythorpe, K. A. COVID-19 impact on routine immunisations for vaccine-preventable diseases: Projecting the effect of different routes to recovery. Vaccine, 40(31), 4142-4149. https://doi.org/10.1016/j.vaccine.2022.05.074

(2022) Ali, H.A., Hartner, AM., Echeverr\'ia-Londo\~no, S,.  et al. Vaccine equity in low and middle-income countries: a systematic review and meta-analysis. Int J Equity Health 21, 82. https://doi.org/10.1186/s12939-022-01678-5

(2021) Echeverr\'ia-Londo\~no, S,.  Li, X., Toor, J., de-Villiers, M., Nayagam, S., Hallett, T.B., Abbas, K., Jit, M., Klepac, P., Jean, K. \&  Garske, T. How can the public health impact of vaccination be estimated? BMC Public Health, 21, 2049 (2021). https://doi.org/10.1186/s12889-021-12040-9

(2021) Toor, J., Echeverr\'ia-Londo\~no, S,. Li, X., Abbas, K., Carter, E. D., Clapham, H. E., ... \& Gaythorpe, K. A. Lives saved with vaccination for 10 pathogens across 112 countries in a pre-COVID-19 world, eLife 10, e67635.https://doi.org/10.7554/eLife.67635

(2021) Gaythorpe, K. A., Toor, J., Echeverr\'ia-Londo\~no, S,.  Li, X., \& Ferguson, N. M. Vaccines can save children with non-preventable diseases Authors' reply.  Estimating the health impact of vaccination against ten pathogens in 98 low-income and middle-income countries from 2000 to 2030: a modelling study, The Lancet 397(10291), 2251. https://doi.org/10.1016/S0140-6736(21)01015-1

(2021) Li, X., Mukandavire, C., Cucunub\'a, Z. M., Echeverr\'ia-Londo\~no, S,. Abbas, K., Clapham, H. E., ... \& et al.  Estimating the health impact of vaccination against ten pathogens in 98 low-income and middle-income countries from 2000 to 2030: a modelling study, The Lancet,  397(10272), 398-408. https://doi.org/10.1016/S0140-6736(20)32657-X

(2021) Gaythorpe K, Abbas K, Huber J, Karachaliou A, Thakkar N, Woodruff K, Li X, Echeverr\'ia-Londo\~no, S,.  Ferrari M, Jackson ML, McCarthy K. Impact of COVID-19-related disruptions to measles, meningococcal A, and yellow fever vaccination in 10 countries, eLife, 2021;10:e67023. https://doi.org/10.7554/elife.67023
