---
title: "The PREDICTS database: a global database of how local terrestrial biodiversity responds to human impacts"
type: "article"
author: "Lawrence N. Hudson, Tim Newbold, Sara Contu, Samantha L. L. Hill, Igor Lysenko, Adriana De Palma, Helen R. P. Phillips, Rebecca A. Senior, Dominic J. Bennett, Hollie Booth, Argyrios Choimes, David L. P. Correia, Julie Day, Susy Echeverría‐Londoño, Morgan Garon, Michelle L. K. Harrison, Daniel J. Ingram, Martin Jung, Victoria Kemp, Lucinda Kirkpatrick, Callum D. Martin, Yuan Pan, Hannah J. White, Job Aben, Stefan Abrahamczyk, Gilbert B. Adum, Virginia Aguilar‐Barquero, Marcelo A. Aizen, Marc Ancrenaz, Enrique Arbeláez‐Cortés, Inge Armbrecht, Badrul Azhar, Adrián B. Azpiroz, Lander Baeten, András Báldi, John E. Banks, Jos Barlow, Péter Batáry, Adam J. Bates, Erin M. Bayne, Pedro Beja, Åke Berg, Nicholas J. Berry, Jake E. Bicknell, Jochen H. Bihn, Katrin Böhning‐Gaese, Teun Boekhout, Céline Boutin, Jérémy Bouyer, Francis Q. Brearley, Isabel Brito, Jörg Brunet, Grzegorz Buczkowski, Erika Buscardo, Jimmy Cabra‐García, María Calviño‐Cancela, Sydney A. Cameron, Eliana M. Cancello, Tiago F. Carrijo, Anelena L. Carvalho, Helena Castro, Alejandro A. Castro‐Luna, Rolando Cerda, Alexis Cerezo, Matthieu Chauvat, Frank M. Clarke, Daniel F. R. Cleary, Stuart P. Connop, Biagio D'Aniello, Pedro Giovâni da Silva, Ben Darvill, Jens Dauber, Alain Dejean, Tim Diekötter, Yamileth Dominguez‐Haydar, Carsten F. Dormann, Bertrand Dumont, Simon G. Dures, Mats Dynesius, Lars Edenius, Zoltán Elek, Martin H. Entling, Nina Farwig, Tom M. Fayle, Antonio Felicioli, Annika M. Felton, Gentile F. Ficetola, Bruno K. C. Filgueiras, Steven J. Fonte, Lauchlan H. Fraser, Daisuke Fukuda, Dario Furlani, Jörg U. Ganzhorn, Jenni G. Garden, Carla Gheler‐Costa, Paolo Giordani, Simonetta Giordano, Marco S. Gottschalk, Dave Goulson, Aaron D. Gove, James Grogan, Mick E. Hanley, Thor Hanson, Nor R. Hashim, Joseph E. Hawes, Christian Hébert, Alvin J. Helden, John‐André Henden, Lionel Hernández, Felix Herzog, Diego Higuera‐Diaz, Branko Hilje, Finbarr G. Horgan, Roland Horváth, Kristoffer Hylander, Paola Isaacs‐Cubides, Masahiro Ishitani, Carmen T. Jacobs, Víctor J. Jaramillo, Birgit Jauker, Mats Jonsell, Thomas S. Jung, Vena Kapoor, Vassiliki Kati, Eric Katovai, Michael Kessler, Eva Knop, Annette Kolb, Ádám Kőrösi, Thibault Lachat, Victoria Lantschner, Violette Le Féon, Gretchen LeBuhn, Jean‐Philippe Légaré, Susan G. Letcher, Nick A. Littlewood, Carlos A. López‐Quintero, Mounir Louhaichi, Gabor L. Lövei, Manuel Esteban Lucas‐Borja, Victor H. Luja, Kaoru Maeto, Tibor Magura, Neil Aldrin Mallari, Erika Marin‐Spiotta, E. J. P. Marshall, Eliana Martínez, Margaret M. Mayfield, Grzegorz Mikusinski, Jeffrey C. Milder, James R. Miller, Carolina L. Morales, Mary N. Muchane, Muchai Muchane, Robin Naidoo, Akihiro Nakamura, Shoji Naoe, Guiomar Nates‐Parra, Dario A. Navarrete Gutierrez, Eike L. Neuschulz, Norbertas Noreika, Olivia Norfolk, Jorge Ari Noriega, Nicole M. Nöske, Niall O'Dea, William Oduro, Caleb Ofori‐Boateng, Chris O. Oke, Lynne M. Osgathorpe, Juan Paritsis, Alejandro Parra‐H, Nicolás Pelegrin, Carlos A. Peres, Anna S. Persson, Theodora Petanidou, Ben Phalan, T. Keith Philips, Katja Poveda, Eileen F. Power, Steven J. Presley, Vânia Proença, Marino Quaranta, Carolina Quintero, Nicola A. Redpath‐Downing, J. Leighton Reid, Yana T. Reis, Danilo B. Ribeiro, Barbara A. Richardson, Michael J. Richardson, Carolina A. Robles, Jörg Römbke, Luz Piedad Romero‐Duque, Loreta Rosselli, Stephen J. Rossiter, T'ai H. Roulston, Laurent Rousseau, Jonathan P. Sadler, Szabolcs Sáfián, Romeo A. Saldaña‐Vázquez, Ulrika Samnegård, Christof Schüepp, Oliver Schweiger, Jodi L. Sedlock, Ghazala Shahabuddin, Douglas Sheil, Fernando A. B. Silva, Eleanor M. Slade, Allan H. Smith‐Pardo, Navjot S. Sodhi, Eduardo J. Somarriba, Ramón A. Sosa, Jane C. Stout, Matthew J. Struebig, Yik‐Hei Sung, Caragh G. Threlfall, Rebecca Tonietto, Béla Tóthmérész, Teja Tscharntke, Edgar C. Turner, Jason M. Tylianakis, Adam J. Vanbergen, Kiril Vassilev, Hans A. F. Verboven, Carlos H. Vergara, Pablo M. Vergara, Jort Verhulst, Tony R. Walker, Yanping Wang, James I. Watling, Konstans Wells, Christopher D. Williams, Michael R. Willig, John C. Z. Woinarski, Jan H. D. Wolf, Ben A. Woodcock, Douglas W. Yu, Andrey S. Zaitsev, Ben Collen, Rob M. Ewers, Georgina M. Mace, Drew W. Purves, Jörn P. W. Scharlemann, Andy Purvis"
year: "2014"
doi: "10.1002/ece3.1303"
categories: []
---

# Abstract
<p> Biodiversity continues to decline in the face of increasing anthropogenic pressures such as habitat destruction, exploitation, pollution and introduction of alien species. Existing global databases of species’ threat status or population time series are dominated by charismatic species. The collation of datasets with broad taxonomic and biogeographic extents, and that support computation of a range of biodiversity indicators, is necessary to enable better understanding of historical declines and to project – and avert – future declines. We describe and assess a new database of more than 1.6 million samples from 78 countries representing over 28,000 species, collated from existing spatial comparisons of local‐scale biodiversity exposed to different intensities and types of anthropogenic pressures, from terrestrial sites around the world. The database contains measurements taken in 208 (of 814) ecoregions, 13 (of 14) biomes, 25 (of 35) biodiversity hotspots and 16 (of 17) megadiverse countries. The database contains more than 1% of the total number of all species described, and more than 1% of the described species within many taxonomic groups – including flowering plants, gymnosperms, birds, mammals, reptiles, amphibians, beetles, lepidopterans and hymenopterans. The dataset, which is still being added to, is therefore already considerably larger and more representative than those used by previous quantitative models of biodiversity trends and responses. The database is being assembled as part of the <styled-content style = "fixed-case">PREDICTS</styled-content> project (Projecting Responses of Ecological Diversity In Changing Terrestrial Systems – <ext-link href = "https://www.nhm.ac.uk/our-science/our-work/biodiversity/predicts.html">https://www.nhm.ac.uk/our-science/our-work/biodiversity/predicts.html</ext-link> ). We make site‐level summary data available alongside this article. The full database will be publicly available in 2015. </p>

# Citation (APA)
Lawrence N. Hudson, Tim Newbold, Sara Contu, Samantha L. L. Hill, Igor Lysenko, Adriana De Palma, Helen R. P. Phillips, Rebecca A. Senior, Dominic J. Bennett, Hollie Booth, Argyrios Choimes, David L. P. Correia, Julie Day, Susy Echeverría‐Londoño, Morgan Garon, Michelle L. K. Harrison, Daniel J. Ingram, Martin Jung, Victoria Kemp, Lucinda Kirkpatrick, Callum D. Martin, Yuan Pan, Hannah J. White, Job Aben, Stefan Abrahamczyk, Gilbert B. Adum, Virginia Aguilar‐Barquero, Marcelo A. Aizen, Marc Ancrenaz, Enrique Arbeláez‐Cortés, Inge Armbrecht, Badrul Azhar, Adrián B. Azpiroz, Lander Baeten, András Báldi, John E. Banks, Jos Barlow, Péter Batáry, Adam J. Bates, Erin M. Bayne, Pedro Beja, Åke Berg, Nicholas J. Berry, Jake E. Bicknell, Jochen H. Bihn, Katrin Böhning‐Gaese, Teun Boekhout, Céline Boutin, Jérémy Bouyer, Francis Q. Brearley, Isabel Brito, Jörg Brunet, Grzegorz Buczkowski, Erika Buscardo, Jimmy Cabra‐García, María Calviño‐Cancela, Sydney A. Cameron, Eliana M. Cancello, Tiago F. Carrijo, Anelena L. Carvalho, Helena Castro, Alejandro A. Castro‐Luna, Rolando Cerda, Alexis Cerezo, Matthieu Chauvat, Frank M. Clarke, Daniel F. R. Cleary, Stuart P. Connop, Biagio D'Aniello, Pedro Giovâni da Silva, Ben Darvill, Jens Dauber, Alain Dejean, Tim Diekötter, Yamileth Dominguez‐Haydar, Carsten F. Dormann, Bertrand Dumont, Simon G. Dures, Mats Dynesius, Lars Edenius, Zoltán Elek, Martin H. Entling, Nina Farwig, Tom M. Fayle, Antonio Felicioli, Annika M. Felton, Gentile F. Ficetola, Bruno K. C. Filgueiras, Steven J. Fonte, Lauchlan H. Fraser, Daisuke Fukuda, Dario Furlani, Jörg U. Ganzhorn, Jenni G. Garden, Carla Gheler‐Costa, Paolo Giordani, Simonetta Giordano, Marco S. Gottschalk, Dave Goulson, Aaron D. Gove, James Grogan, Mick E. Hanley, Thor Hanson, Nor R. Hashim, Joseph E. Hawes, Christian Hébert, Alvin J. Helden, John‐André Henden, Lionel Hernández, Felix Herzog, Diego Higuera‐Diaz, Branko Hilje, Finbarr G. Horgan, Roland Horváth, Kristoffer Hylander, Paola Isaacs‐Cubides, Masahiro Ishitani, Carmen T. Jacobs, Víctor J. Jaramillo, Birgit Jauker, Mats Jonsell, Thomas S. Jung, Vena Kapoor, Vassiliki Kati, Eric Katovai, Michael Kessler, Eva Knop, Annette Kolb, Ádám Kőrösi, Thibault Lachat, Victoria Lantschner, Violette Le Féon, Gretchen LeBuhn, Jean‐Philippe Légaré, Susan G. Letcher, Nick A. Littlewood, Carlos A. López‐Quintero, Mounir Louhaichi, Gabor L. Lövei, Manuel Esteban Lucas‐Borja, Victor H. Luja, Kaoru Maeto, Tibor Magura, Neil Aldrin Mallari, Erika Marin‐Spiotta, E. J. P. Marshall, Eliana Martínez, Margaret M. Mayfield, Grzegorz Mikusinski, Jeffrey C. Milder, James R. Miller, Carolina L. Morales, Mary N. Muchane, Muchai Muchane, Robin Naidoo, Akihiro Nakamura, Shoji Naoe, Guiomar Nates‐Parra, Dario A. Navarrete Gutierrez, Eike L. Neuschulz, Norbertas Noreika, Olivia Norfolk, Jorge Ari Noriega, Nicole M. Nöske, Niall O'Dea, William Oduro, Caleb Ofori‐Boateng, Chris O. Oke, Lynne M. Osgathorpe, Juan Paritsis, Alejandro Parra‐H, Nicolás Pelegrin, Carlos A. Peres, Anna S. Persson, Theodora Petanidou, Ben Phalan, T. Keith Philips, Katja Poveda, Eileen F. Power, Steven J. Presley, Vânia Proença, Marino Quaranta, Carolina Quintero, Nicola A. Redpath‐Downing, J. Leighton Reid, Yana T. Reis, Danilo B. Ribeiro, Barbara A. Richardson, Michael J. Richardson, Carolina A. Robles, Jörg Römbke, Luz Piedad Romero‐Duque, Loreta Rosselli, Stephen J. Rossiter, T'ai H. Roulston, Laurent Rousseau, Jonathan P. Sadler, Szabolcs Sáfián, Romeo A. Saldaña‐Vázquez, Ulrika Samnegård, Christof Schüepp, Oliver Schweiger, Jodi L. Sedlock, Ghazala Shahabuddin, Douglas Sheil, Fernando A. B. Silva, Eleanor M. Slade, Allan H. Smith‐Pardo, Navjot S. Sodhi, Eduardo J. Somarriba, Ramón A. Sosa, Jane C. Stout, Matthew J. Struebig, Yik‐Hei Sung, Caragh G. Threlfall, Rebecca Tonietto, Béla Tóthmérész, Teja Tscharntke, Edgar C. Turner, Jason M. Tylianakis, Adam J. Vanbergen, Kiril Vassilev, Hans A. F. Verboven, Carlos H. Vergara, Pablo M. Vergara, Jort Verhulst, Tony R. Walker, Yanping Wang, James I. Watling, Konstans Wells, Christopher D. Williams, Michael R. Willig, John C. Z. Woinarski, Jan H. D. Wolf, Ben A. Woodcock, Douglas W. Yu, Andrey S. Zaitsev, Ben Collen, Rob M. Ewers, Georgina M. Mace, Drew W. Purves, Jörn P. W. Scharlemann, Andy Purvis (2014). The PREDICTS database: a global database of how local terrestrial biodiversity responds to human impacts *Ecology and Evolution*, 4(24), 4701-4735. 10.1002/ece3.1303

