---
title: "The database of the <scp>PREDICTS</scp> (Projecting Responses of Ecological Diversity In Changing Terrestrial Systems) project"
type: "article"
author: "Lawrence N. Hudson, Tim Newbold, Sara Contu, Samantha L. L. Hill, Igor Lysenko, Adriana De Palma, Helen R. P. Phillips, Tamera I. Alhusseini, Felicity E. Bedford, Dominic J. Bennett, Hollie Booth, Victoria J. Burton, Charlotte W. T. Chng, Argyrios Choimes, David L. P. Correia, Julie Day, Susy Echeverría‐Londoño, Susan R. Emerson, Di Gao, Morgan Garon, Michelle L. K. Harrison, Daniel J. Ingram, Martin Jung, Victoria Kemp, Lucinda Kirkpatrick, Callum D. Martin, Yuan Pan, Gwilym D. Pask‐Hale, Edwin L. Pynegar, Alexandra N. Robinson, Katia Sanchez‐Ortiz, Rebecca A. Senior, Benno I. Simmons, Hannah J. White, Hanbin Zhang, Job Aben, Stefan Abrahamczyk, Gilbert B. Adum, Virginia Aguilar‐Barquero, Marcelo A. Aizen, Belén Albertos, E. L. Alcala, Maria del Mar Alguacil, Audrey Alignier, Marc Ancrenaz, Alan N. Andersen, Enrique Arbeláez‐Cortés, Inge Armbrecht, Víctor Arroyo‐Rodríguez, Tom Aumann, Jan C. Axmacher, Badrul Azhar, Adrián B. Azpiroz, Lander Baeten, Adama Bakayoko, András Báldi, John E. Banks, Sharad K. Baral, Jos Barlow, Barbara I. P. Barratt, Lurdes Barrico, Paola Bartolommei, Diane M. Barton, Yves Basset, Péter Batáry, Adam J. Bates, Bruno Baur, Erin M. Bayne, Pedro Beja, Suzan Benedick, Åke Berg, Henry Bernard, Nicholas J. Berry, Dinesh Bhatt, Jake E. Bicknell, Jochen H. Bihn, Robin J. Blake, Kadiri S. Bobo, Roberto Bóçon, Teun Boekhout, Katrin Böhning‐Gaese, Kevin J. Bonham, Paulo A. V. Borges, Sérgio H. Borges, Céline Boutin, Jérémy Bouyer, Cibele Bragagnolo, Jodi S. Brandt, Francis Q. Brearley, Isabel Brito, Vicenç Bros, Jörg Brunet, Grzegorz Buczkowski, Christopher M. Buddle, Rob Bugter, Erika Buscardo, Jörn Buse, Jimmy Cabra‐García, Nilton C. Cáceres, Nicolette L. Cagle, María Calviño‐Cancela, Sydney A. Cameron, Eliana M. Cancello, Rut Caparrós, Pedro Cardoso, Dan Carpenter, Tiago F. Carrijo, Anelena L. Carvalho, Camila R. Cassano, Helena Castro, Alejandro A. Castro‐Luna, Cerda B. Rolando, Alexis Cerezo, Kim Alan Chapman, Matthieu Chauvat, Morten Christensen, Francis M. Clarke, Daniel F.R. Cleary, Giorgio Colombo, Stuart P. Connop, Michael D. Craig, Leopoldo Cruz‐López, Saul A. Cunningham, Biagio D'Aniello, Neil D'Cruze, Pedro Giovâni da Silva, Martin Dallimer, Emmanuel Danquah, Ben Darvill, Jens Dauber, Adrian L. V. Davis, Jeff Dawson, Claudio de Sassi, Benoit de Thoisy, Olivier Deheuvels, Alain Dejean, Jean‐Louis Devineau, Tim Diekötter, Jignasu V. Dolia, Erwin Domínguez, Yamileth Dominguez‐Haydar, Silvia Dorn, Isabel Draper, Niels Dreber, Bertrand Dumont, Simon G. Dures, Mats Dynesius, Lars Edenius, Paul Eggleton, Felix Eigenbrod, Zoltán Elek, Martin H. Entling, Karen J. Esler, Ricardo F. de Lima, Aisyah Faruk, Nina Farwig, Tom M. Fayle, Antonio Felicioli, Annika M. Felton, Roderick J. Fensham, Ignacio C. Fernandez, Catarina C. Ferreira, Gentile F. Ficetola, Cristina Fiera, Bruno K. C. Filgueiras, Hüseyin K. Fırıncıoğlu, David Flaspohler, Andreas Floren, Steven J. Fonte, Anne Fournier, Robert E. Fowler, Markus Franzén, Lauchlan H. Fraser, Gabriella M. Fredriksson, Geraldo B. Freire, Tiago L. M. Frizzo, Daisuke Fukuda, Dario Furlani, René Gaigher, Jörg U. Ganzhorn, Karla P. García, Juan C. Garcia‐R, Jenni G. Garden, Ricardo Garilleti, Bao‐Ming Ge, Benoit Gendreau‐Berthiaume, Philippa J. Gerard, Carla Gheler‐Costa, Benjamin Gilbert, Paolo Giordani, Simonetta Giordano, Carly Golodets, Laurens G. L. Gomes, Rachelle K. Gould, Dave Goulson, Aaron D. Gove, Laurent Granjon, Ingo Grass, Claudia L. Gray, James Grogan, Weibin Gu, Moisès Guardiola, Nihara R. Gunawardene, Alvaro G. Gutierrez, Doris L. Gutiérrez‐Lamus, Daniela H. Haarmeyer, Mick E. Hanley, Thor Hanson, Nor R. Hashim, Shombe N. Hassan, Richard G. Hatfield, Joseph E. Hawes, Matt W. Hayward, Christian Hébert, Alvin J. Helden, John‐André Henden, Philipp Henschel, Lionel Hernández, James P. Herrera, Farina Herrmann, Felix Herzog, Diego Higuera‐Diaz, Branko Hilje, Hubert Höfer, Anke Hoffmann, Finbarr G. Horgan, Elisabeth Hornung, Roland Horváth, Kristoffer Hylander, Paola Isaacs‐Cubides, Hiroaki Ishida, Masahiro Ishitani, Carmen T. Jacobs, Víctor J. Jaramillo, Birgit Jauker, F. Jiménez Hernández, McKenzie F. Johnson, Virat Jolli, Mats Jonsell, S. Nur Juliani, Thomas S. Jung, Vena Kapoor, Heike Kappes, Vassiliki Kati, Eric Katovai, Klaus Kellner, Michael Kessler, Kathryn R. Kirby, Andrew M. Kittle, Mairi E. Knight, Eva Knop, Florian Kohler, Matti Koivula, Annette Kolb, Mouhamadou Kone, Ádám Kőrösi, Jochen Krauss, Ajith Kumar, Raman Kumar, David J. Kurz, Alex S. Kutt, Thibault Lachat, Victoria Lantschner, Francisco Lara, Jesse R. Lasky, Steven C. Latta, William F. Laurance, Patrick Lavelle, Violette Le Féon, Gretchen LeBuhn, Jean‐Philippe Légaré, Valérie Lehouck, María V. Lencinas, Pia E. Lentini, Susan G. Letcher, Qi Li, Simon A. Litchwark, Nick A. Littlewood, Yunhui Liu, Nancy Lo‐Man‐Hung, Carlos A. López‐Quintero, Mounir Louhaichi, Gabor L. Lövei, Manuel Esteban Lucas‐Borja, Victor H. Luja, Matthew S. Luskin, M Cristina MacSwiney G, Kaoru Maeto, Tibor Magura, Neil Aldrin Mallari, Louise A. Malone, Patrick K. Malonza, Jagoba Malumbres‐Olarte, Salvador Mandujano, Inger E. Måren, Erika Marin‐Spiotta, Charles J. Marsh, E. J. P. Marshall, Eliana Martínez, Guillermo Martínez Pastur, David Moreno Mateos, Margaret M. Mayfield, Vicente Mazimpaka, Jennifer L. McCarthy, Kyle P. McCarthy, Quinn S. McFrederick, Sean McNamara, Nagore G. Medina, Rafael Medina, Jose L. Mena, Estefania Mico, Grzegorz Mikusinski, Jeffrey C. Milder, James R. Miller, Daniel R. Miranda‐Esquivel, Melinda L. Moir, Carolina L. Morales, Mary N. Muchane, Muchai Muchane, Sonja Mudri‐Stojnic, A. Nur Munira, Antonio Muoñz‐Alonso, B. F. Munyekenye, Robin Naidoo, A. Naithani, Michiko Nakagawa, Akihiro Nakamura, Yoshihiro Nakashima, Shoji Naoe, Guiomar Nates‐Parra, Dario A. Navarrete Gutierrez, Luis Navarro‐Iriarte, Paul K. Ndang'ang'a, Eike L. Neuschulz, Jacqueline T. Ngai, Violaine Nicolas, Sven G. Nilsson, Norbertas Noreika, Olivia Norfolk, Jorge Ari Noriega, David A. Norton, Nicole M. Nöske, A. Justin Nowakowski, Catherine Numa, Niall O'Dea, Patrick J. O'Farrell, William Oduro, Sabine Oertli, Caleb Ofori‐Boateng, Christopher Omamoke Oke, Vicencio Oostra, Lynne M. Osgathorpe, Samuel Eduardo Otavo, Navendu V. Page, Juan Paritsis, Alejandro Parra‐H, Luke Parry, Guy Pe'er, Peter B. Pearman, Nicolás Pelegrin, Raphaël Pélissier, Carlos A. Peres, Pablo L. Peri, Anna S. Persson, Theodora Petanidou, Marcell K. Peters, Rohan S. Pethiyagoda, Ben Phalan, T. Keith Philips, Finn C. Pillsbury, Jimmy Pincheira‐Ulbrich, Eduardo Pineda, Joan Pino, Jaime Pizarro‐Araya, A. J. Plumptre, Santiago L. Poggio, Natalia Politi, Pere Pons, Katja Poveda, Eileen F. Power, Steven J. Presley, Vânia Proença, Marino Quaranta, Carolina Quintero, Romina Rader, B. R. Ramesh, Martha P. Ramirez‐Pinilla, Jai Ranganathan, Claus Rasmussen, Nicola A. Redpath‐Downing, J. Leighton Reid, Yana T. Reis, José M. Rey Benayas, Juan Carlos Rey‐Velasco, Chevonne Reynolds, Danilo Bandini Ribeiro, Miriam H. Richards, Barbara A. Richardson, Michael J. Richardson, Rodrigo Macip Ríos, Richard Robinson, Carolina A. Robles, Jörg Römbke, Luz Piedad Romero‐Duque, Matthias Rös, Loreta Rosselli, Stephen J. Rossiter, Dana S. Roth, T'ai H. Roulston, Laurent Rousseau, André V. Rubio, Jean‐Claude Ruel, Jonathan P. Sadler, Szabolcs Sáfián, Romeo A. Saldaña‐Vázquez, Katerina Sam, Ulrika Samnegård, Joana Santana, Xavier Santos, Jade Savage, Nancy A. Schellhorn, Menno Schilthuizen, Ute Schmiedel, Christine B. Schmitt, Nicole L. Schon, Christof Schüepp, Katharina Schumann, Oliver Schweiger, Dawn M. Scott, Kenneth A. Scott, Jodi L. Sedlock, Steven S. Seefeldt, Ghazala Shahabuddin, Graeme Shannon, Douglas Sheil, Frederick H. Sheldon, Eyal Shochat, Stefan J. Siebert, Fernando A. B. Silva, Javier A. Simonetti, Eleanor M. Slade, Jo Smith, Allan H. Smith‐Pardo, Navjot S. Sodhi, Eduardo J. Somarriba, Ramón A. Sosa, Grimaldo Soto Quiroga, Martin‐Hugues St‐Laurent, Brian M. Starzomski, Constanti Stefanescu, Ingolf Steffan‐Dewenter, Philip C. Stouffer, Jane C. Stout, Ayron M. Strauch, Matthew J. Struebig, Zhimin Su, Marcela Suarez‐Rubio, Shinji Sugiura, Keith S. Summerville, Yik‐Hei Sung, Hari Sutrisno, Jens‐Christian Svenning, Tiit Teder, Caragh G. Threlfall, Anu Tiitsaar, Jacqui H. Todd, Rebecca K. Tonietto, Ignasi Torre, Béla Tóthmérész, Teja Tscharntke, Edgar C. Turner, Jason M. Tylianakis, Marcio Uehara‐Prado, Nicolas Urbina‐Cardona, Denis Vallan, Adam J. Vanbergen, Heraldo L. Vasconcelos, Kiril Vassilev, Hans A. F. Verboven, Maria João Verdasca, José R. Verdú, Carlos H. Vergara, Pablo M. Vergara, Jort Verhulst, Massimiliano Virgilio, Lien Van Vu, Edward M. Waite, Tony R. Walker, Hua‐Feng Wang, Yanping Wang, James I. Watling, Britta Weller, Konstans Wells, Catrin Westphal, Edward D. Wiafe, Christopher D. Williams, Michael R. Willig, John C. Z. Woinarski, Jan H. D. Wolf, Volkmar Wolters, Ben A. Woodcock, Jihua Wu, Joseph M. Wunderle, Yuichi Yamaura, Satoko Yoshikura, Douglas W. Yu, Andrey S. Zaitsev, Juliane Zeidler, Fasheng Zou, Ben Collen, Rob M. Ewers, Georgina M. Mace, Drew W. Purves, Jörn P. W. Scharlemann, Andy Purvis"
year: "2017"
doi: "10.1002/ece3.2579"
categories: []
---

# Abstract
<p> The <styled-content style = "fixed-case">PREDICTS</styled-content> project—Projecting Responses of Ecological Diversity In Changing Terrestrial Systems ( <ext-link href = "https://www.nhm.ac.uk/our-science/our-work/biodiversity/predicts.html">https://www.nhm.ac.uk/our-science/our-work/biodiversity/predicts.html</ext-link> )—has collated from published studies a large, reasonably representative database of comparable samples of biodiversity from multiple sites that differ in the nature or intensity of human impacts relating to land use. We have used this evidence base to develop global and regional statistical models of how local biodiversity responds to these measures. We describe and make freely available this 2016 release of the database, containing more than 3.2 million records sampled at over 26,000 locations and representing over 47,000 species. We outline how the database can help in answering a range of questions in ecology and conservation biology. To our knowledge, this is the largest and most geographically and taxonomically representative database of spatial comparisons of biodiversity that has been collated to date; it will be useful to researchers and international efforts wishing to model and understand the global status of biodiversity. </p>

# Citation (APA)
Lawrence N. Hudson, Tim Newbold, Sara Contu, Samantha L. L. Hill, Igor Lysenko, Adriana De Palma, Helen R. P. Phillips, Tamera I. Alhusseini, Felicity E. Bedford, Dominic J. Bennett, Hollie Booth, Victoria J. Burton, Charlotte W. T. Chng, Argyrios Choimes, David L. P. Correia, Julie Day, Susy Echeverría‐Londoño, Susan R. Emerson, Di Gao, Morgan Garon, Michelle L. K. Harrison, Daniel J. Ingram, Martin Jung, Victoria Kemp, Lucinda Kirkpatrick, Callum D. Martin, Yuan Pan, Gwilym D. Pask‐Hale, Edwin L. Pynegar, Alexandra N. Robinson, Katia Sanchez‐Ortiz, Rebecca A. Senior, Benno I. Simmons, Hannah J. White, Hanbin Zhang, Job Aben, Stefan Abrahamczyk, Gilbert B. Adum, Virginia Aguilar‐Barquero, Marcelo A. Aizen, Belén Albertos, E. L. Alcala, Maria del Mar Alguacil, Audrey Alignier, Marc Ancrenaz, Alan N. Andersen, Enrique Arbeláez‐Cortés, Inge Armbrecht, Víctor Arroyo‐Rodríguez, Tom Aumann, Jan C. Axmacher, Badrul Azhar, Adrián B. Azpiroz, Lander Baeten, Adama Bakayoko, András Báldi, John E. Banks, Sharad K. Baral, Jos Barlow, Barbara I. P. Barratt, Lurdes Barrico, Paola Bartolommei, Diane M. Barton, Yves Basset, Péter Batáry, Adam J. Bates, Bruno Baur, Erin M. Bayne, Pedro Beja, Suzan Benedick, Åke Berg, Henry Bernard, Nicholas J. Berry, Dinesh Bhatt, Jake E. Bicknell, Jochen H. Bihn, Robin J. Blake, Kadiri S. Bobo, Roberto Bóçon, Teun Boekhout, Katrin Böhning‐Gaese, Kevin J. Bonham, Paulo A. V. Borges, Sérgio H. Borges, Céline Boutin, Jérémy Bouyer, Cibele Bragagnolo, Jodi S. Brandt, Francis Q. Brearley, Isabel Brito, Vicenç Bros, Jörg Brunet, Grzegorz Buczkowski, Christopher M. Buddle, Rob Bugter, Erika Buscardo, Jörn Buse, Jimmy Cabra‐García, Nilton C. Cáceres, Nicolette L. Cagle, María Calviño‐Cancela, Sydney A. Cameron, Eliana M. Cancello, Rut Caparrós, Pedro Cardoso, Dan Carpenter, Tiago F. Carrijo, Anelena L. Carvalho, Camila R. Cassano, Helena Castro, Alejandro A. Castro‐Luna, Cerda B. Rolando, Alexis Cerezo, Kim Alan Chapman, Matthieu Chauvat, Morten Christensen, Francis M. Clarke, Daniel F.R. Cleary, Giorgio Colombo, Stuart P. Connop, Michael D. Craig, Leopoldo Cruz‐López, Saul A. Cunningham, Biagio D'Aniello, Neil D'Cruze, Pedro Giovâni da Silva, Martin Dallimer, Emmanuel Danquah, Ben Darvill, Jens Dauber, Adrian L. V. Davis, Jeff Dawson, Claudio de Sassi, Benoit de Thoisy, Olivier Deheuvels, Alain Dejean, Jean‐Louis Devineau, Tim Diekötter, Jignasu V. Dolia, Erwin Domínguez, Yamileth Dominguez‐Haydar, Silvia Dorn, Isabel Draper, Niels Dreber, Bertrand Dumont, Simon G. Dures, Mats Dynesius, Lars Edenius, Paul Eggleton, Felix Eigenbrod, Zoltán Elek, Martin H. Entling, Karen J. Esler, Ricardo F. de Lima, Aisyah Faruk, Nina Farwig, Tom M. Fayle, Antonio Felicioli, Annika M. Felton, Roderick J. Fensham, Ignacio C. Fernandez, Catarina C. Ferreira, Gentile F. Ficetola, Cristina Fiera, Bruno K. C. Filgueiras, Hüseyin K. Fırıncıoğlu, David Flaspohler, Andreas Floren, Steven J. Fonte, Anne Fournier, Robert E. Fowler, Markus Franzén, Lauchlan H. Fraser, Gabriella M. Fredriksson, Geraldo B. Freire, Tiago L. M. Frizzo, Daisuke Fukuda, Dario Furlani, René Gaigher, Jörg U. Ganzhorn, Karla P. García, Juan C. Garcia‐R, Jenni G. Garden, Ricardo Garilleti, Bao‐Ming Ge, Benoit Gendreau‐Berthiaume, Philippa J. Gerard, Carla Gheler‐Costa, Benjamin Gilbert, Paolo Giordani, Simonetta Giordano, Carly Golodets, Laurens G. L. Gomes, Rachelle K. Gould, Dave Goulson, Aaron D. Gove, Laurent Granjon, Ingo Grass, Claudia L. Gray, James Grogan, Weibin Gu, Moisès Guardiola, Nihara R. Gunawardene, Alvaro G. Gutierrez, Doris L. Gutiérrez‐Lamus, Daniela H. Haarmeyer, Mick E. Hanley, Thor Hanson, Nor R. Hashim, Shombe N. Hassan, Richard G. Hatfield, Joseph E. Hawes, Matt W. Hayward, Christian Hébert, Alvin J. Helden, John‐André Henden, Philipp Henschel, Lionel Hernández, James P. Herrera, Farina Herrmann, Felix Herzog, Diego Higuera‐Diaz, Branko Hilje, Hubert Höfer, Anke Hoffmann, Finbarr G. Horgan, Elisabeth Hornung, Roland Horváth, Kristoffer Hylander, Paola Isaacs‐Cubides, Hiroaki Ishida, Masahiro Ishitani, Carmen T. Jacobs, Víctor J. Jaramillo, Birgit Jauker, F. Jiménez Hernández, McKenzie F. Johnson, Virat Jolli, Mats Jonsell, S. Nur Juliani, Thomas S. Jung, Vena Kapoor, Heike Kappes, Vassiliki Kati, Eric Katovai, Klaus Kellner, Michael Kessler, Kathryn R. Kirby, Andrew M. Kittle, Mairi E. Knight, Eva Knop, Florian Kohler, Matti Koivula, Annette Kolb, Mouhamadou Kone, Ádám Kőrösi, Jochen Krauss, Ajith Kumar, Raman Kumar, David J. Kurz, Alex S. Kutt, Thibault Lachat, Victoria Lantschner, Francisco Lara, Jesse R. Lasky, Steven C. Latta, William F. Laurance, Patrick Lavelle, Violette Le Féon, Gretchen LeBuhn, Jean‐Philippe Légaré, Valérie Lehouck, María V. Lencinas, Pia E. Lentini, Susan G. Letcher, Qi Li, Simon A. Litchwark, Nick A. Littlewood, Yunhui Liu, Nancy Lo‐Man‐Hung, Carlos A. López‐Quintero, Mounir Louhaichi, Gabor L. Lövei, Manuel Esteban Lucas‐Borja, Victor H. Luja, Matthew S. Luskin, M Cristina MacSwiney G, Kaoru Maeto, Tibor Magura, Neil Aldrin Mallari, Louise A. Malone, Patrick K. Malonza, Jagoba Malumbres‐Olarte, Salvador Mandujano, Inger E. Måren, Erika Marin‐Spiotta, Charles J. Marsh, E. J. P. Marshall, Eliana Martínez, Guillermo Martínez Pastur, David Moreno Mateos, Margaret M. Mayfield, Vicente Mazimpaka, Jennifer L. McCarthy, Kyle P. McCarthy, Quinn S. McFrederick, Sean McNamara, Nagore G. Medina, Rafael Medina, Jose L. Mena, Estefania Mico, Grzegorz Mikusinski, Jeffrey C. Milder, James R. Miller, Daniel R. Miranda‐Esquivel, Melinda L. Moir, Carolina L. Morales, Mary N. Muchane, Muchai Muchane, Sonja Mudri‐Stojnic, A. Nur Munira, Antonio Muoñz‐Alonso, B. F. Munyekenye, Robin Naidoo, A. Naithani, Michiko Nakagawa, Akihiro Nakamura, Yoshihiro Nakashima, Shoji Naoe, Guiomar Nates‐Parra, Dario A. Navarrete Gutierrez, Luis Navarro‐Iriarte, Paul K. Ndang'ang'a, Eike L. Neuschulz, Jacqueline T. Ngai, Violaine Nicolas, Sven G. Nilsson, Norbertas Noreika, Olivia Norfolk, Jorge Ari Noriega, David A. Norton, Nicole M. Nöske, A. Justin Nowakowski, Catherine Numa, Niall O'Dea, Patrick J. O'Farrell, William Oduro, Sabine Oertli, Caleb Ofori‐Boateng, Christopher Omamoke Oke, Vicencio Oostra, Lynne M. Osgathorpe, Samuel Eduardo Otavo, Navendu V. Page, Juan Paritsis, Alejandro Parra‐H, Luke Parry, Guy Pe'er, Peter B. Pearman, Nicolás Pelegrin, Raphaël Pélissier, Carlos A. Peres, Pablo L. Peri, Anna S. Persson, Theodora Petanidou, Marcell K. Peters, Rohan S. Pethiyagoda, Ben Phalan, T. Keith Philips, Finn C. Pillsbury, Jimmy Pincheira‐Ulbrich, Eduardo Pineda, Joan Pino, Jaime Pizarro‐Araya, A. J. Plumptre, Santiago L. Poggio, Natalia Politi, Pere Pons, Katja Poveda, Eileen F. Power, Steven J. Presley, Vânia Proença, Marino Quaranta, Carolina Quintero, Romina Rader, B. R. Ramesh, Martha P. Ramirez‐Pinilla, Jai Ranganathan, Claus Rasmussen, Nicola A. Redpath‐Downing, J. Leighton Reid, Yana T. Reis, José M. Rey Benayas, Juan Carlos Rey‐Velasco, Chevonne Reynolds, Danilo Bandini Ribeiro, Miriam H. Richards, Barbara A. Richardson, Michael J. Richardson, Rodrigo Macip Ríos, Richard Robinson, Carolina A. Robles, Jörg Römbke, Luz Piedad Romero‐Duque, Matthias Rös, Loreta Rosselli, Stephen J. Rossiter, Dana S. Roth, T'ai H. Roulston, Laurent Rousseau, André V. Rubio, Jean‐Claude Ruel, Jonathan P. Sadler, Szabolcs Sáfián, Romeo A. Saldaña‐Vázquez, Katerina Sam, Ulrika Samnegård, Joana Santana, Xavier Santos, Jade Savage, Nancy A. Schellhorn, Menno Schilthuizen, Ute Schmiedel, Christine B. Schmitt, Nicole L. Schon, Christof Schüepp, Katharina Schumann, Oliver Schweiger, Dawn M. Scott, Kenneth A. Scott, Jodi L. Sedlock, Steven S. Seefeldt, Ghazala Shahabuddin, Graeme Shannon, Douglas Sheil, Frederick H. Sheldon, Eyal Shochat, Stefan J. Siebert, Fernando A. B. Silva, Javier A. Simonetti, Eleanor M. Slade, Jo Smith, Allan H. Smith‐Pardo, Navjot S. Sodhi, Eduardo J. Somarriba, Ramón A. Sosa, Grimaldo Soto Quiroga, Martin‐Hugues St‐Laurent, Brian M. Starzomski, Constanti Stefanescu, Ingolf Steffan‐Dewenter, Philip C. Stouffer, Jane C. Stout, Ayron M. Strauch, Matthew J. Struebig, Zhimin Su, Marcela Suarez‐Rubio, Shinji Sugiura, Keith S. Summerville, Yik‐Hei Sung, Hari Sutrisno, Jens‐Christian Svenning, Tiit Teder, Caragh G. Threlfall, Anu Tiitsaar, Jacqui H. Todd, Rebecca K. Tonietto, Ignasi Torre, Béla Tóthmérész, Teja Tscharntke, Edgar C. Turner, Jason M. Tylianakis, Marcio Uehara‐Prado, Nicolas Urbina‐Cardona, Denis Vallan, Adam J. Vanbergen, Heraldo L. Vasconcelos, Kiril Vassilev, Hans A. F. Verboven, Maria João Verdasca, José R. Verdú, Carlos H. Vergara, Pablo M. Vergara, Jort Verhulst, Massimiliano Virgilio, Lien Van Vu, Edward M. Waite, Tony R. Walker, Hua‐Feng Wang, Yanping Wang, James I. Watling, Britta Weller, Konstans Wells, Catrin Westphal, Edward D. Wiafe, Christopher D. Williams, Michael R. Willig, John C. Z. Woinarski, Jan H. D. Wolf, Volkmar Wolters, Ben A. Woodcock, Jihua Wu, Joseph M. Wunderle, Yuichi Yamaura, Satoko Yoshikura, Douglas W. Yu, Andrey S. Zaitsev, Juliane Zeidler, Fasheng Zou, Ben Collen, Rob M. Ewers, Georgina M. Mace, Drew W. Purves, Jörn P. W. Scharlemann, Andy Purvis (2017). The database of the <scp>PREDICTS</scp> (Projecting Responses of Ecological Diversity In Changing Terrestrial Systems) project *Ecology and Evolution*, 7(1), 145-188. 10.1002/ece3.2579

