---
title: "Estimating the health impact of vaccination against ten pathogens in 98 low-income and middle-income countries from 2000 to 2030: a modelling study"
type: "article"
author: "Xiang Li, Christinah Mukandavire, Zulma M Cucunuba, Susy Echeverria-Londono, Kaja Abbas, Hannah E. Clapham, Mark Jit, Hope L Johnson, Timos Papadopoulos, Emilia Vynnycky, Marc Brisson, Emily D. Carter, Andrew Clark, Margaret J. de Villiers, Kirsten Eilertson, Matthew J. Ferrari, Ivane Gamkrelidze, Katy A. M. Gaythorpe, Nicholas C. Grassly, Timothy B. Hallett, Wes Hinsley, Michael L. Jackson, Kevin Jean, Andromachi Karachaliou, Petra Klepac, Justin Lessler, Xi Li, Sean M. Moore, Shevanthi Nayagam, Duy Manh Nguyen, Homie Razavi, Devin Razavi-Shearer, Stephen Resch, Colin Sanderson, Steven Sweet, Stephen Sy, Yvonne Tam, Hira Tanvir, Quan Minh Tran, Caroline L. Trotter, Shaun Truelove, Kevin van Zandvoort, Stéphane Verguet, Neff Walker, Amy Winter, Kim Woodruff, Neil M. Ferguson, Tini Garske"
year: "2021"
doi: "10.1016/S0140-6736(20)32657-X"
categories: []
---

# Abstract
No abstract available.

# Citation (APA)
Xiang Li, Christinah Mukandavire, Zulma M Cucunuba, Susy Echeverria-Londono, Kaja Abbas, Hannah E. Clapham, Mark Jit, Hope L Johnson, Timos Papadopoulos, Emilia Vynnycky, Marc Brisson, Emily D. Carter, Andrew Clark, Margaret J. de Villiers, Kirsten Eilertson, Matthew J. Ferrari, Ivane Gamkrelidze, Katy A. M. Gaythorpe, Nicholas C. Grassly, Timothy B. Hallett, Wes Hinsley, Michael L. Jackson, Kevin Jean, Andromachi Karachaliou, Petra Klepac, Justin Lessler, Xi Li, Sean M. Moore, Shevanthi Nayagam, Duy Manh Nguyen, Homie Razavi, Devin Razavi-Shearer, Stephen Resch, Colin Sanderson, Steven Sweet, Stephen Sy, Yvonne Tam, Hira Tanvir, Quan Minh Tran, Caroline L. Trotter, Shaun Truelove, Kevin van Zandvoort, Stéphane Verguet, Neff Walker, Amy Winter, Kim Woodruff, Neil M. Ferguson, Tini Garske (2021). Estimating the health impact of vaccination against ten pathogens in 98 low-income and middle-income countries from 2000 to 2030: a modelling study *The Lancet*, 397(10272), 398-408. 10.1016/S0140-6736(20)32657-X

