---
title: "COVID-19 impact on routine immunisations for vaccine-preventable diseases: Projecting the effect of different routes to recovery"
type: "article"
author: "Jaspreet Toor, Xiang Li, Mark Jit, Caroline L. Trotter, Susy Echeverria-Londono, Anna-Maria Hartner, Jeremy Roth, Allison Portnoy, Kaja Abbas, Neil M. Ferguson, Katy AM Gaythorpe"
year: "2022"
doi: "10.1016/j.vaccine.2022.05.074"
categories: []
---

# Abstract
Over the past two decades, vaccination programmes for vaccine-preventable diseases (VPDs) have expanded across low- and middle-income countries (LMICs). However, the rise of COVID-19 resulted in global disruption to routine immunisation activities. Such disruptions could have a detrimental effect on public health, leading to more deaths from VPDs, particularly without mitigation efforts. Hence, as routine immunisation activities resume, it is important to estimate the effectiveness of different approaches for recovery. We apply an impact extrapolation method developed by the Vaccine Impact Modelling Consortium to estimate the impact of COVID-19-related disruptions with different recovery scenarios for ten VPDs across 112 LMICs. We focus on deaths averted due to routine immunisations occurring in the years 2020–2030 and investigate two recovery scenarios relative to a no-COVID-19 scenario. In the recovery scenarios, we assume a 10% COVID-19-related drop in routine immunisation coverage in the year 2020. We then linearly interpolate coverage to the year 2030 to investigate two routes to recovery, whereby the immunization agenda (IA2030) targets are reached by 2030 or fall short by 10%. We estimate that falling short of the IA2030 targets by 10% leads to 11.26% fewer fully vaccinated persons (FVPs) and 11.34% more deaths over the years 2020–2030 relative to the no-COVID-19 scenario, whereas, reaching the IA2030 targets reduces these proportions to 5% fewer FVPs and 5.22% more deaths. The impact of the disruption varies across the VPDs with diseases where coverage expands drastically in future years facing a smaller detrimental effect. Overall, our results show that drops in routine immunisation coverage could result in more deaths due to VPDs. As the impact of COVID-19-related disruptions is dependent on the vaccination coverage that is achieved over the coming years, the continued efforts of building up coverage and addressing gaps in immunity are vital in the road to recovery.

# Citation (APA)
Jaspreet Toor, Xiang Li, Mark Jit, Caroline L. Trotter, Susy Echeverria-Londono, Anna-Maria Hartner, Jeremy Roth, Allison Portnoy, Kaja Abbas, Neil M. Ferguson, Katy AM Gaythorpe (2022). COVID-19 impact on routine immunisations for vaccine-preventable diseases: Projecting the effect of different routes to recovery *Vaccine*, 40(31), 4142-4149. 10.1016/j.vaccine.2022.05.074

